name = "gr8r-uploadsign-worker"
main = "index.js"
compatibility_date = "2025-07-11"
workers_dev = false
account_id = "6a22f9b8ad27ffcc9719dd53a78bcedf"

[[routes]]
pattern = "uploads.gr8r.com/*"
zone_name = "gr8r.com"

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "videos-gr8r"
